repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1 # 4.2.0 drops python3.6 support
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^patch/
      - id: check-yaml

#  - repo: https://gitlab.esss.lu.se/e3/dbformat
#    rev: 0.4.2
#    hooks:
#      - id: dbformat
